config/routes.rb
Rails.application.routes.draw do
  resources :players
  resources :transfermarkts
  resources :managers
  resources :auths, only: [:create]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/manager.rb
class Manager < ApplicationRecord
    has_many :players
    accepts_nested_attributes_for :players, allow_destroy: true

    def as_json(options = {})
        super(include: :players)
    end
end

app/controllers/managers_controller.rb
class ManagersController < ApplicationController
  before_action :set_manager, only: %i[ show edit update destroy ]

  # GET /managers or /managers.json
  def index
    @managers = Manager.all

    # Cache controll with etag
    if stale?(etag: @managers)
      render json: @managers, include: :players
    end
  end
  # GET /managers/1 or /managers/1.json
  def show
    render json: @manager, include: :players
  end

  # GET /managers/new
  def new
    @manager = Manager.new
  end

  # GET /managers/1/edit
  def edit
  end

  # POST /managers or /managers.json
  def create
    @manager = Manager.new(manager_params)

    respond_to do |format|
      if @manager.save
        format.html { redirect_to manager_url(@manager), notice: "Manager was successfully created." }
        format.json { render :show, status: :created, location: @manager }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @manager.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /managers/1 or /managers/1.json
  def update
    respond_to do |format|
      if @manager.update(manager_params)
        format.html { redirect_to manager_url(@manager), notice: "Manager was successfully updated." }
        format.json { render :show, status: :ok, location: @manager }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @manager.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /managers/1 or /managers/1.json
  def destroy
    @manager.destroy

    respond_to do |format|
      format.html { redirect_to managers_url, notice: "Manager was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_manager
      @manager = Manager.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def manager_params
      params.require(:manager).permit(
        :name, 
        :email, 
        :nationality, 
        :workteam
      )
    end
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/views/managers/_form.html.erb
<%= form_with(model: manager) do |form| %>
  <% if manager.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(manager.errors.count, "error") %> prohibited this manager from being saved:</h2>

      <ul>
        <% manager.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :nationality, style: "display: block" %>
    <%= form.text_field :nationality %>
  </div>

  <div>
    <%= form.label :workteam, style: "display: block" %>
    <%= form.text_field :workteam %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/managers/_manager.html.erb
<div id="<%= dom_id manager %>">
  <p>
    <strong>Name:</strong>
    <%= manager.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= manager.email %>
  </p>

  <p>
    <strong>Nationality:</strong>
    <%= manager.nationality %>
  </p>

  <p>
    <strong>Workteam:</strong>
    <%= manager.workteam %>
  </p>

</div>

app/views/managers/edit.html.erb
<h1>Editing manager</h1>

<%= render "form", manager: @manager %>

<br>

<div>
  <%= link_to "Show this manager", @manager %> |
  <%= link_to "Back to managers", managers_path %>
</div>

app/views/managers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Managers</h1>

<div id="managers">
  <% @managers.each do |manager| %>
    <%= render manager %>
    <p>
      <%= link_to "Show this manager", manager %>
    </p>
  <% end %>
</div>

<%= link_to "New manager", new_manager_path %>

app/views/managers/new.html.erb
<h1>New manager</h1>

<%= render "form", manager: @manager %>

<br>

<div>
  <%= link_to "Back to managers", managers_path %>
</div>

app/views/managers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @manager %>

<div>
  <%= link_to "Edit this manager", edit_manager_path(@manager) %> |
  <%= link_to "Back to managers", managers_path %>

  <%= button_to "Destroy this manager", @manager, method: :delete %>
</div>