config/routes.rb
Rails.application.routes.draw do
  resources :players
  resources :transfermarkts
  resources :managers
  resources :auths, only: [:create]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/transfermarkt.rb
class Transfermarkt < ApplicationRecord
    has_many :players
    accepts_nested_attributes_for :players, allow_destroy: true

    def as_json(options = {})
        super(include: :players)
    end
end

app/controllers/transfermarkts_controller.rb
class TransfermarktsController < ApplicationController
  before_action :set_transfermarkt, only: %i[ show edit update destroy ]

  # GET /transfermarkts or /transfermarkts.json
  def index
    @transfermarkts = Transfermarkt.all
    # Cache controll with etag
    if stale?(etag: @transfermarkts)
      render json: @transfermarkts, include: :players
    end
  end
  # GET /transfermarkts/1 or /transfermarkts/1.json
  def show
    render json: @transfermarkts, include: :players
  end

  # GET /transfermarkts/new
  def new
    @transfermarkt = Transfermarkt.new
  end

  # GET /transfermarkts/1/edit
  def edit
  end

  # POST /transfermarkts or /transfermarkts.json
  def create
    @transfermarkt = Transfermarkt.new(transfermarkt_params)

    respond_to do |format|
      if @transfermarkt.save
        format.html { redirect_to transfermarkt_url(@transfermarkt), notice: "Transfermarkt was successfully created." }
        format.json { render :show, status: :created, location: @transfermarkt }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @transfermarkt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transfermarkts/1 or /transfermarkts/1.json
  def update
    respond_to do |format|
      if @transfermarkt.update(transfermarkt_params)
        format.html { redirect_to transfermarkt_url(@transfermarkt), notice: "Transfermarkt was successfully updated." }
        format.json { render :show, status: :ok, location: @transfermarkt }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @transfermarkt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transfermarkts/1 or /transfermarkts/1.json
  def destroy
    @transfermarkt.destroy

    respond_to do |format|
      format.html { redirect_to transfermarkts_url, notice: "Transfermarkt was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transfermarkt
      @transfermarkt = Transfermarkt.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def transfermarkt_params
      params.require(:transfermarkt).permit(
        :description, 
        :crypto, 
        :timezone
      )
    end
end

app/helpers/transfermarkts_helper.rb
module TransfermarktsHelper
end

app/views/transfermarkts/_form.html.erb
<%= form_with(model: transfermarkt) do |form| %>
  <% if transfermarkt.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(transfermarkt.errors.count, "error") %> prohibited this transfermarkt from being saved:</h2>

      <ul>
        <% transfermarkt.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :crypto, style: "display: block" %>
    <%= form.text_field :crypto %>
  </div>

  <div>
    <%= form.label :timezone, style: "display: block" %>
    <%= form.text_field :timezone %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/transfermarkts/_transfermarkt.html.erb
<div id="<%= dom_id transfermarkt %>">
  <p>
    <strong>Description:</strong>
    <%= transfermarkt.description %>
  </p>

  <p>
    <strong>Crypto:</strong>
    <%= transfermarkt.crypto %>
  </p>

  <p>
    <strong>Timezone:</strong>
    <%= transfermarkt.timezone %>
  </p>

</div>

app/views/transfermarkts/edit.html.erb
<h1>Editing transfermarkt</h1>

<%= render "form", transfermarkt: @transfermarkt %>

<br>

<div>
  <%= link_to "Show this transfermarkt", @transfermarkt %> |
  <%= link_to "Back to transfermarkts", transfermarkts_path %>
</div>

app/views/transfermarkts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Transfermarkts</h1>

<div id="transfermarkts">
  <% @transfermarkts.each do |transfermarkt| %>
    <%= render transfermarkt %>
    <p>
      <%= link_to "Show this transfermarkt", transfermarkt %>
    </p>
  <% end %>
</div>

<%= link_to "New transfermarkt", new_transfermarkt_path %>

app/views/transfermarkts/new.html.erb
<h1>New transfermarkt</h1>

<%= render "form", transfermarkt: @transfermarkt %>

<br>

<div>
  <%= link_to "Back to transfermarkts", transfermarkts_path %>
</div>

app/views/transfermarkts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @transfermarkt %>

<div>
  <%= link_to "Edit this transfermarkt", edit_transfermarkt_path(@transfermarkt) %> |
  <%= link_to "Back to transfermarkts", transfermarkts_path %>

  <%= button_to "Destroy this transfermarkt", @transfermarkt, method: :delete %>
</div>